#if !canImport(ObjectiveC)
import XCTest

extension ApplicationExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationExtensionsTests = [
        ("testCacheDirectory", testCacheDirectory),
        ("testDocumentsDirectory", testDocumentsDirectory),
        ("testNewDocument", testNewDocument),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApplicationExtensionsTests.__allTests__ApplicationExtensionsTests),
    ]
}
#endif
